### ISSUE TITLE
restore works not for openshift

### ISSUE THREAD

**Issue by mark-00** [maorfr/helm-restore#3]
Hi

The code uses kubectl and I got some errors because I use it on openshift

helm restore  --tiller-ns tiller isor-prod
2019/01/24 17:04:39 Error: command execution failed: [kubectl apply --namespace isor-prod -f 

I forked the code and changed kubectl by oc
Works like a charm

I see you have done a lot of work on helm. What's the best way to make this generic ?

Mark

**Comment by maorfr** [comment]
I suppose we can add a `--oc` flag that will force using oc instead of kubectl.
Not sure yet if this is the best way, but I bet I will find out soon enough.

Would you like to implement this or should I? :)
